[package]
name = "uniffi-bindgen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
